[testServer]

BROKER_HOST = 100.89.78.6
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[testDMZ]

BROKER_HOST = 100.89.78.6
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = dmzExchange
QUEUE = dmzQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

